import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Aura Smart Lamp',
    description: 'Mood-lifting smart lamp with customizable colors.',
    longDescription: 'The Aura Smart Lamp brings vibrant, customizable lighting to any room. Control millions of colors and shades of white light from your smartphone. Set schedules, create scenes, and sync the light to your music for an immersive experience. Its minimalist design blends seamlessly into any decor.',
    price: 79.99,
    image: '1',
    category: 'Electronics',
    tags: ['new', 'popular'],
    stock: 150,
  },
  {
    id: 'prod_002',
    name: 'Flow Mechanical Keyboard',
    description: 'A quiet and tactile typing experience for professionals.',
    longDescription: 'Experience typing nirvana with the Flow Mechanical Keyboard. Featuring quiet, tactile switches, a solid aluminum frame, and smart backlighting, this keyboard is designed for focus and productivity. The compact layout saves desk space while providing a full-sized typing feel.',
    price: 159.0,
    image: '2',
    category: 'Office',
    tags: ['popular'],
    stock: 80,
  },
  {
    id: 'prod_003',
    name: 'Eco-Carry Tote Bag',
    description: 'Stylish and durable tote made from recycled materials.',
    longDescription: 'Carry your essentials in style with the Eco-Carry Tote Bag. Made from 100% recycled canvas, this durable and spacious bag is perfect for daily use, from grocery runs to beach trips. It features an internal pocket for your valuables and reinforced straps for comfort.',
    price: 45.5,
    image: '3',
    category: 'Lifestyle',
    tags: ['eco-friendly', 'sale'],
    stock: 200,
  },
  {
    id: 'prod_004',
    name: 'Zenith Wireless Earbuds',
    description: 'Crystal-clear audio with active noise cancellation.',
    longDescription: 'Immerse yourself in pure sound with Zenith Wireless Earbuds. Active noise cancellation silences distractions, while the custom-tuned drivers deliver rich, high-fidelity audio. Enjoy up to 30 hours of listening time with the compact charging case.',
    price: 129.99,
    image: '4',
    category: 'Electronics',
    tags: ['popular', 'new'],
    stock: 120,
  },
  {
    id: 'prod_005',
    name: 'Orbit Desk Organizer',
    description: 'Modular magnetic desk organizer for a tidy workspace.',
    longDescription: 'Declutter your desk with the Orbit Desk Organizer. This modular system uses powerful magnets to let you customize your layout. It includes a phone stand, pen holder, and trays for small items, all crafted from premium walnut wood and anodized aluminum.',
    price: 65.0,
    image: '5',
    category: 'Office',
    tags: [],
    stock: 180,
  },
  {
    id: 'prod_006',
    name: 'Pure-Mist Humidifier',
    description: 'Ultrasonic cool mist humidifier for a healthier home.',
    longDescription: 'Breathe easier with the Pure-Mist Humidifier. Its ultrasonic technology produces a fine, cool mist to add essential moisture to the air, helping to relieve dry skin and sinuses. The large tank provides up to 24 hours of continuous operation, and it doubles as an essential oil diffuser.',
    price: 55.0,
    image: '6',
    category: 'Lifestyle',
    tags: ['sale'],
    stock: 90,
  },
  {
    id: 'prod_007',
    name: 'Momentum Smart Watch',
    description: 'Track your fitness and stay connected in style.',
    longDescription: 'The Momentum Smart Watch is the perfect companion for an active life. It tracks your steps, heart rate, and sleep, offers multiple sport modes, and delivers notifications straight to your wrist. With a vibrant AMOLED display and a 14-day battery life, it keeps up with you.',
    price: 199.0,
    image: '7',
    category: 'Electronics',
    tags: ['new'],
    stock: 75,
  },
  {
    id: 'prod_008',
    name: 'Creator Fountain Pen',
    description: 'A classic writing instrument for the modern writer.',
    longDescription: 'Rediscover the joy of writing with the Creator Fountain Pen. With a balanced, weighted body and a smooth-writing German-engineered nib, it offers an unparalleled writing experience. Each pen is precision-milled from a single block of brass for a lifetime of use.',
    price: 89.99,
    image: '8',
    category: 'Office',
    tags: [],
    stock: 110,
  },
  {
    id: 'prod_009',
    name: 'Nomad Travel Backpack',
    description: 'Versatile and secure backpack for travel and daily commute.',
    longDescription: 'The Nomad Travel Backpack is engineered for the modern traveler. It features a lay-flat main compartment for easy packing, a padded laptop sleeve, and multiple pockets for organization. The weatherproof sailcloth exterior and anti-theft zippers keep your gear safe.',
    price: 175.0,
    image: '9',
    category: 'Lifestyle',
    tags: ['popular'],
    stock: 60,
  },
  {
    id: 'prod_010',
    name: 'Power-Up Charging Station',
    description: 'Charge all your devices in one sleek hub.',
    longDescription: 'Simplify your charging routine with the Power-Up Charging Station. This hub can wirelessly charge your phone and earbuds, and has a dedicated stand for your smartwatch. An additional USB-C port provides fast charging for another device. It\'s the only charger you need on your nightstand.',
    price: 110.0,
    image: '10',
    category: 'Electronics',
    tags: [],
    stock: 130,
  },
  {
    id: 'prod_011',
    name: 'Ergo-Pro Office Chair',
    description: 'Ergonomic support for all-day comfort and focus.',
    longDescription: 'Invest in your well-being with the Ergo-Pro Office Chair. Fully adjustable, it offers dynamic lumbar support, a breathable mesh back, and a synchro-tilt mechanism to promote healthy posture. Designed to provide comfort through long hours of work or gaming.',
    price: 399.0,
    image: '11',
    category: 'Office',
    tags: ['popular'],
    stock: 40,
  },
  {
    id: 'prod_012',
    name: 'Terra Recycled Beanie',
    description: 'Cozy and stylish beanie made from recycled polyester.',
    longDescription: 'Stay warm and sustainable with the Terra Recycled Beanie. This classic ribbed beanie is made from soft, 100% recycled polyester yarn, making it a stylish and eco-conscious choice for cold weather. One size fits most.',
    price: 35.0,
    image: '12',
    category: 'Lifestyle',
    tags: ['eco-friendly', 'new'],
    stock: 250,
  },
];

export const categories = [...new Set(products.map((p) => p.category))];
export const tags = [...new Set(products.flatMap((p) => p.tags))];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByIds(ids: string[]): Product[] {
  return products.filter((p) => ids.includes(p.id));
}
